import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"

type Content = Record<string, any>

export function ScenarioEditor({ content, editable, save }: { content: Content; editable: boolean; save: (content: Content) => void }) {
  const [draft, setDraft] = useState<Content>(structuredClone(content))
  const [advanced, setAdvanced] = useState(JSON.stringify(content, null, 2))
  const [error, setError] = useState("")
  useEffect(() => { setDraft(structuredClone(content)); setAdvanced(JSON.stringify(content, null, 2)) }, [content])
  if (!content.calendar) return <p className="text-sm text-amber-700">Det äldre scenariot saknar terminsformulär. Kopiera terminsmallen för ändringsbara kalender- och bemanningsregler.</p>
  const calendar = draft.calendar || {}; const staffing = draft.staffing || {}; const costs = draft.costs || {}; const conflicts = draft.conflicts || {}
  const update = (section: string, key: string, value: unknown) => setDraft(current => ({ ...current, [section]: { ...current[section], [key]: value } }))
  const updateBound = (key: "start_date" | "end_date", value: string) => setDraft(current => {
    const calendar = current.calendar || {}; const periods = (calendar.period || []).map((period: Content) => period[key] === calendar[key] ? { ...period, [key]: value } : period)
    return { ...current, calendar: { ...calendar, [key]: value, period: periods } }
  })
  const updateRow = (section: string, name: string, index: number, key: string, value: unknown) => setDraft(current => {
    const rows = [...(current[section]?.[name] || [])]; rows[index] = { ...rows[index], [key]: value }
    return { ...current, [section]: { ...current[section], [name]: rows } }
  })
  const updatePeriod = (index: number, key: string, value: unknown) => setDraft(current => {
    const periods = [...(current.calendar?.period || [])]; periods[index] = { ...periods[index], [key]: value }
    return { ...current, calendar: { ...current.calendar, period: periods } }
  })
  const submitAdvanced = () => { try { const parsed = JSON.parse(advanced) as Content; setDraft(parsed); save(parsed); setError("") } catch { setError("Den avancerade konfigurationen måste vara giltig JSON.") } }
  return <div className="space-y-5">
    <section>
      <h3 className="mb-3 text-sm font-semibold">Kalender och skrivpass</h3>
      <div className="grid gap-3 md:grid-cols-4"><Field label="Terminsstart" type="date" value={calendar.start_date} disabled={!editable} onChange={value => updateBound("start_date", value)}/><Field label="Terminslut" type="date" value={calendar.end_date} disabled={!editable} onChange={value => updateBound("end_date", value)}/><Field label="Ställtid (minuter)" type="number" value={calendar.turnaround_minutes} disabled={!editable} onChange={value => update("calendar", "turnaround_minutes", Number(value))}/><Weekdays value={calendar.allowed_weekdays || []} disabled={!editable} onChange={value => update("calendar", "allowed_weekdays", value)}/></div>
      <EditableTable title="Skrivpass" headers={["Pass", "Start", "Senaste slut"]} rows={calendar.passes || []} disabled={!editable} fields={["pass_id", "start_time", "latest_end_time"]} types={["text", "time", "time"]} update={(index, key, value) => updateRow("calendar", "passes", index, key, value)}/>
      <EditableTable title="Kalenderperioder" headers={["Period", "Start", "Slut"]} rows={calendar.period || []} disabled={!editable} fields={["period_id", "start_date", "end_date"]} types={["text", "date", "date"]} update={updatePeriod}/>
    </section>
    <section className="border-t pt-4">
      <h3 className="mb-3 text-sm font-semibold">Bemanning och kostnad</h3>
      <div className="grid gap-3 md:grid-cols-3"><Field label="Grundbemanning per sal" type="number" value={staffing.staff_per_room_session} disabled={!editable} onChange={value => update("staffing", "staff_per_room_session", Number(value))}/><Field label="Årskostnad per vakt (öre)" type="number" value={staffing.annual_cost_ore_per_staff} disabled={!editable} onChange={value => update("staffing", "annual_cost_ore_per_staff", Number(value))}/><Field label="Årskostnad per lokalplats (öre)" type="number" value={costs.annual_room_cost_ore_per_seat} disabled={!editable} onChange={value => update("costs", "annual_room_cost_ore_per_seat", Number(value))}/><Field label="Förberedelse (minuter)" type="number" value={staffing.preparation_minutes} disabled={!editable} onChange={value => update("staffing", "preparation_minutes", Number(value))}/><Field label="Avslut (minuter)" type="number" value={staffing.closing_minutes} disabled={!editable} onChange={value => update("staffing", "closing_minutes", Number(value))}/><Field label="Restid mellan byggnader" type="number" value={staffing.travel_minutes_between_buildings} disabled={!editable} onChange={value => update("staffing", "travel_minutes_between_buildings", Number(value))}/><Field label="Minsta rast (minuter)" type="number" value={staffing.minimum_break_minutes} disabled={!editable} onChange={value => update("staffing", "minimum_break_minutes", Number(value))}/><Field label="Max sammanhängande tid" type="number" value={staffing.maximum_continuous_minutes} disabled={!editable} onChange={value => update("staffing", "maximum_continuous_minutes", Number(value))}/><Field label="Max arbetstid per dygn" type="number" value={staffing.maximum_daily_minutes} disabled={!editable} onChange={value => update("staffing", "maximum_daily_minutes", Number(value))}/><Field label="Minsta dygnsvila" type="number" value={staffing.minimum_daily_rest_minutes} disabled={!editable} onChange={value => update("staffing", "minimum_daily_rest_minutes", Number(value))}/></div>
      <EditableTable title="Bemanningstrappa" headers={["Upp till deltagare", "Vakter"]} rows={staffing.ladder || []} disabled={!editable} fields={["up_to_participants", "staff_required"]} types={["number", "number"]} update={(index, key, value) => updateRow("staffing", "ladder", index, key, Number(value))}/>
      <EditableTable title="Arbetspass" headers={["Pass", "Start", "Slut"]} rows={staffing.shift || []} disabled={!editable} fields={["shift_id", "start_time", "end_time"]} types={["text", "time", "time"]} update={(index, key, value) => updateRow("staffing", "shift", index, key, value)}/>
    </section>
    <section className="border-t pt-4"><h3 className="mb-3 text-sm font-semibold">Kompatibilitet och krockregler</h3><div className="grid gap-3 md:grid-cols-2"><SelectField label="Digital kompatibilitet" value={draft.compatibility?.digital_compatibility_mode || ""} disabled={!editable} onChange={value => update("compatibility", "digital_compatibility_mode", value)} options={["all_exploratory_candidate_rooms_assumed_compatible_with_observed_formats"]}/><Field label="Krockpolicy" type="text" value={conflicts.policy} disabled={!editable} onChange={value => update("conflicts", "policy", value)}/><Field label="Status för programrelationer" type="text" value={conflicts.program_relation_data_status} disabled={!editable} onChange={value => update("conflicts", "program_relation_data_status", value)}/></div></section>
    <section className="border-t pt-4"><h3 className="mb-2 text-sm font-semibold">Antaganden och verifieringsstatus</h3><p className="mb-2 text-xs text-slate-500">Värdena synkroniseras från formulärets faktiska beräkningsparametrar när scenariot sparas.</p><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-slate-500"><th className="p-1">Antagande</th><th>Värde</th><th>Enhet</th><th>Källa</th><th>Status</th></tr></thead><tbody>{(draft.assumption || []).map((item: Content) => <tr className="border-t" key={item.id}><td className="p-1 font-medium">{item.id}</td><td>{item.value}</td><td>{item.unit}</td><td>{item.source}</td><td>{item.status}</td></tr>)}</tbody></table></div></section>
    {editable && <div className="flex justify-end"><Button onClick={() => save(draft)}>Spara parameterändringar</Button></div>}
    <details className="border-t pt-3"><summary className="cursor-pointer text-xs font-medium text-slate-600">Avancerad JSON-konfiguration</summary><textarea className="field mt-2 h-48 font-mono text-xs" value={advanced} disabled={!editable} onChange={event => setAdvanced(event.target.value)}/>{error && <p className="mt-1 text-xs text-red-700">{error}</p>}{editable && <Button size="sm" className="mt-2" variant="outline" onClick={submitAdvanced}>Spara avancerad konfiguration</Button>}</details>
  </div>
}

function EditableTable({ title, headers, rows, fields, types, disabled, update }: { title: string; headers: string[]; rows: Content[]; fields: string[]; types: string[]; disabled: boolean; update: (index: number, key: string, value: string) => void }) { return <div className="mt-3 overflow-x-auto"><div className="label">{title}</div><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500">{headers.map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{fields.map((field, fieldIndex) => <td className="py-1 pr-2" key={field}><input className="field" type={types[fieldIndex]} value={row[field] ?? ""} disabled={disabled} onChange={event => update(index, field, event.target.value)}/></td>)}</tr>)}</tbody></table></div> }
function Field({ label, type, value, disabled, onChange }: { label: string; type: string; value: unknown; disabled: boolean; onChange: (value: string) => void }) { return <label><span className="label">{label}</span><input className="field" type={type} value={value == null ? "" : String(value)} disabled={disabled} onChange={event => onChange(event.target.value)}/></label> }
function SelectField({ label, value, disabled, onChange, options }: { label: string; value: string; disabled: boolean; onChange: (value: string) => void; options: string[] }) { return <label><span className="label">{label}</span><select className="field" value={value || ""} disabled={disabled} onChange={event => onChange(event.target.value)}>{options.map(option => <option key={option}>{option}</option>)}</select></label> }
function Weekdays({ value, disabled, onChange }: { value: number[]; disabled: boolean; onChange: (value: number[]) => void }) { return <div><span className="label">Tillåtna veckodagar</span><div className="flex h-9 items-center gap-1">{["M", "Ti", "O", "To", "F", "L", "S"].map((name, index) => <label key={name} className="text-xs"><input type="checkbox" checked={value.includes(index + 1)} disabled={disabled} onChange={() => onChange(value.includes(index + 1) ? value.filter(day => day !== index + 1) : [...value, index + 1])}/>{name}</label>)}</div></div> }
