import { useEffect, useState } from "react"
import { Button } from "@/components/ui/button"

type Content = Record<string, any>

export function ScenarioEditor({ content, editable, save }: { content: Content; editable: boolean; save: (content: Content) => void }) {
  const [draft, setDraft] = useState<Content>(structuredClone(content))
  const [advanced, setAdvanced] = useState(JSON.stringify(content, null, 2))
  const [error, setError] = useState("")
  useEffect(() => { setDraft(structuredClone(content)); setAdvanced(JSON.stringify(content, null, 2)) }, [content])
  const update = (section: string, key: string, value: unknown) => setDraft(current => ({ ...current, [section]: { ...current[section], [key]: value } }))
  const updatePass = (index: number, key: string, value: string) => setDraft(current => {
    const passes = [...(current.calendar?.passes || [])]; passes[index] = { ...passes[index], [key]: value }
    return { ...current, calendar: { ...current.calendar, passes } }
  })
  const updateLadder = (index: number, key: string, value: number) => setDraft(current => {
    const ladder = [...(current.staffing?.ladder || [])]; ladder[index] = { ...ladder[index], [key]: value }
    return { ...current, staffing: { ...current.staffing, ladder } }
  })
  const submitAdvanced = () => { try { const parsed = JSON.parse(advanced) as Content; setDraft(parsed); save(parsed); setError("") } catch { setError("Den avancerade konfigurationen måste vara giltig JSON.") } }
  if (!content.calendar) return <p className="text-sm text-amber-700">Det äldre scenariot saknar terminsformulär. Kopiera terminsmallen för ändringsbara kalender- och bemanningsregler.</p>
  const calendar = draft.calendar || {}; const staffing = draft.staffing || {}; const costs = draft.costs || {}
  return <div className="space-y-5">
    <section><h3 className="mb-3 text-sm font-semibold">Kalender och skrivpass</h3><div className="grid gap-3 md:grid-cols-4"><Field label="Terminsstart" type="date" value={calendar.start_date} disabled={!editable} onChange={value => update("calendar", "start_date", value)}/><Field label="Terminslut" type="date" value={calendar.end_date} disabled={!editable} onChange={value => update("calendar", "end_date", value)}/><Field label="Ställtid (minuter)" type="number" value={calendar.turnaround_minutes} disabled={!editable} onChange={value => update("calendar", "turnaround_minutes", Number(value))}/><Weekdays value={calendar.allowed_weekdays || []} disabled={!editable} onChange={value => update("calendar", "allowed_weekdays", value)}/></div><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500"><th className="pb-1">Pass</th><th>Start</th><th>Senaste slut</th></tr></thead><tbody>{(calendar.passes || []).map((pass: Content, index: number) => <tr key={`${pass.pass_id}-${index}`}><td className="py-1 pr-2"><input className="field" value={pass.pass_id} disabled={!editable} onChange={event => updatePass(index, "pass_id", event.target.value)}/></td><td className="py-1 pr-2"><input className="field" type="time" value={pass.start_time} disabled={!editable} onChange={event => updatePass(index, "start_time", event.target.value)}/></td><td className="py-1"><input className="field" type="time" value={pass.latest_end_time} disabled={!editable} onChange={event => updatePass(index, "latest_end_time", event.target.value)}/></td></tr>)}</tbody></table></div></section>
    <section className="border-t pt-4"><h3 className="mb-3 text-sm font-semibold">Bemanning och kostnad</h3><div className="grid gap-3 md:grid-cols-3"><Field label="Grundbemanning per sal" type="number" value={staffing.staff_per_room_session} disabled={!editable} onChange={value => update("staffing", "staff_per_room_session", Number(value))}/><Field label="Årskostnad per vakt (öre)" type="number" value={staffing.annual_cost_ore_per_staff} disabled={!editable} onChange={value => update("staffing", "annual_cost_ore_per_staff", Number(value))}/><Field label="Årskostnad per lokalplats (öre)" type="number" value={costs.annual_room_cost_ore_per_seat} disabled={!editable} onChange={value => update("costs", "annual_room_cost_ore_per_seat", Number(value))}/><Field label="Förberedelse (minuter)" type="number" value={staffing.preparation_minutes} disabled={!editable} onChange={value => update("staffing", "preparation_minutes", Number(value))}/><Field label="Avslut (minuter)" type="number" value={staffing.closing_minutes} disabled={!editable} onChange={value => update("staffing", "closing_minutes", Number(value))}/><Field label="Restid mellan byggnader" type="number" value={staffing.travel_minutes_between_buildings} disabled={!editable} onChange={value => update("staffing", "travel_minutes_between_buildings", Number(value))}/></div><div className="mt-3"><div className="label">Bemanningstrappa</div>{(staffing.ladder || []).map((step: Content, index: number) => <div className="mb-2 grid max-w-md grid-cols-2 gap-2" key={index}><Field label="Upp till deltagare" type="number" value={step.up_to_participants} disabled={!editable} onChange={value => updateLadder(index, "up_to_participants", Number(value))}/><Field label="Vakter" type="number" value={step.staff_required} disabled={!editable} onChange={value => updateLadder(index, "staff_required", Number(value))}/></div>)}</div></section>
    <section className="border-t pt-4"><h3 className="mb-2 text-sm font-semibold">Antaganden och verifieringsstatus</h3><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left text-slate-500"><th className="p-1">Antagande</th><th>Värde</th><th>Enhet</th><th>Källa</th><th>Status</th></tr></thead><tbody>{(draft.assumption || []).map((item: Content) => <tr className="border-t" key={item.id}><td className="p-1 font-medium">{item.id}</td><td>{item.value}</td><td>{item.unit}</td><td>{item.source}</td><td>{item.status}</td></tr>)}</tbody></table></div></section>
    {editable && <div className="flex justify-end"><Button onClick={() => save(draft)}>Spara parameterändringar</Button></div>}
    <details className="border-t pt-3"><summary className="cursor-pointer text-xs font-medium text-slate-600">Avancerad JSON-konfiguration</summary><textarea className="field mt-2 h-48 font-mono text-xs" value={advanced} disabled={!editable} onChange={event => setAdvanced(event.target.value)}/>{error && <p className="mt-1 text-xs text-red-700">{error}</p>}{editable && <Button size="sm" className="mt-2" variant="outline" onClick={submitAdvanced}>Spara avancerad konfiguration</Button>}</details>
  </div>
}

function Field({ label, type, value, disabled, onChange }: { label: string; type: string; value: unknown; disabled: boolean; onChange: (value: string) => void }) { return <label><span className="label">{label}</span><input className="field" type={type} value={value == null ? "" : String(value)} disabled={disabled} onChange={event => onChange(event.target.value)}/></label> }

function Weekdays({ value, disabled, onChange }: { value: number[]; disabled: boolean; onChange: (value: number[]) => void }) { return <div><span className="label">Tillåtna veckodagar</span><div className="flex h-9 items-center gap-1">{["M", "Ti", "O", "To", "F", "L", "S"].map((name, index) => <label key={name} className="text-xs"><input type="checkbox" checked={value.includes(index + 1)} disabled={disabled} onChange={() => onChange(value.includes(index + 1) ? value.filter(day => day !== index + 1) : [...value, index + 1])}/>{name}</label>)}</div></div> }
